### ISSUE TITLE
Default login credentials not working

### ISSUE THREAD

**Issue by xinput** [Sanjeet990/Astroluma#11]
Hi,

Just deployed astroluma on my VPS and when trying to login with the credentials that are provided in the documentation, it does not work with the error wrong credentials.

Any support appreciated.

Kind regards

**Comment by Sanjeet990** [comment]
Can you please check and confirm in the container logs that the Db is connecting and data is seeded?

**Comment by xinput** [comment]
Indeed, I should have looked the container logs directly. Sorry. I needed to change the MONGODB_URI in my docker compose to referencce teh container name instead of localhost. That fixed the issue and the app was able to connect to the db.
