### ISSUE TITLE
Stream Hub

### ISSUE THREAD

**Issue by nurhalim88** [Sanjeet990/Astroluma#19]
I have successfully configured RSTP.  Static images confirm the IP camera is operational; however, the live view fails to load, even after an extended wait.

![IMG_20241213_130825_919.jpg](https://github.com/user-attachments/assets/7bbf93d4-f3ef-4111-8249-0abf157595f6)

**Comment by Sanjeet990** [comment]
Static image suggests the setup is correct and the FFMPEG is also working correctly. The socket connection might be failing. 

Two questions?

1. Are you using any Proxy Server such as NGINX Proxy manager to route the traffic?
2. What browser you're using? If you can specify the version, would be helpful.

**Comment by nurhalim88** [comment]
Hi,

Yes, I conducted a few tests. When accessing locally, I'm able to view the live feeds.
1. Currently using Reverse Proxy from Zoraxy (https://zoraxy.aroz.org)
2. Microsoft Edge Version 131.0.2903.86 (Official build) (64-bit)

**Comment by Sanjeet990** [comment]
Great. Streaming uses websockets to stream video. Your Reverse Proxy must support web socket for Stream Hub to work The issue is not with Astroluma but with the Reverse Proxy. I know NGINX Proxy Manager supports web socket, you just need to enable them for specific domain. Zoraxy should also have an option. Please check with Zoraxy documentation.

**Comment by nurhalim88** [comment]
I did check WebSocket is support but encounter below error. 

Encounter below error.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxxxxxxxxxxxxxx.net/675b0b7d415089414602ca18?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU3MmE1N2U5ZmNmZjA5OTgwOTNhMjEiLCJ1c2VybmFtZSI6Im51cmhhbGltODgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQxMTgxMTB9.3E2s8kZuE3U55FRVIJlxUz4pgf6xbctPYCqWD401Q9w'. This request has been blocked; this endpoint must be available over WSS.

**Comment by mariushosting** [comment]
Very bugged the stream part. There is an issue with Astroluma not websocket.

**Comment by Sanjeet990** [comment]
> Very bugged the stream part. There is an issue with Astroluma not websocket.

Would be happy to assist if you can help with some logs may be?

**Comment by Sanjeet990** [comment]
> I did check WebSocket is support but encounter below error.
> 
> Mixed Content: The page at '' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxxxxxxxxxxxxxx.net/675b0b7d415089414602ca18?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU3MmE1N2U5ZmNmZjA5OTgwOTNhMjEiLCJ1c2VybmFtZSI6Im51cmhhbGltODgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQxMTgxMTB9.3E2s8kZuE3U55FRVIJlxUz4pgf6xbctPYCqWD401Q9w'. This request has been blocked; this endpoint must be available over WSS.

Fixed in https://github.com/Sanjeet990/Astroluma/pull/27/commits/aa75dd8261890253081a91a3182c1d1edc55003d

Changes are in development for now. Will be a part of next Astroluma version!
