### ISSUE TITLE
Error: Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by dnielso5** [Sanjeet990/Astroluma#2]
```
> astroluma@1.0.0 server

> cd server && npm run server

> astrolumaserver@1.0.0 server

> node server.js

/app/server/node_modules/sharp/lib/sharp.js:113

  throw new Error(help.join('\n'));

  ^

Error: Could not load the "sharp" module using the linux-x64 runtime

Possible solutions:

- Ensure optional dependencies can be installed:

    npm install --include=optional sharp

- Ensure your package manager supports multi-platform installation:

    See https://sharp.pixelplumbing.com/install#cross-platform

- Add platform-specific dependencies:

    npm install --os=linux --cpu=x64 sharp

- Consult the installation documentation:

    See https://sharp.pixelplumbing.com/install

    at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)

    at Module._compile (node:internal/modules/cjs/loader:1364:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

    at Module.load (node:internal/modules/cjs/loader:1203:32)

    at Module._load (node:internal/modules/cjs/loader:1019:12)

    at Module.require (node:internal/modules/cjs/loader:1231:19)

    at require (node:internal/modules/helpers:177:18)

    at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)

    at Module._compile (node:internal/modules/cjs/loader:1364:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

Node.js v18.20.5
```

when trying to install with Portainer, i get this error

**Comment by dnielso5** [comment]
googlefoo says this might need to add this before npm install in the dockerfile

RUN chown root.root .  # make sure root own the directory before installing Sharp

but im not sure.

**Comment by Sanjeet990** [comment]
Tried to replicate this in some x64 VMs but unfortunately I couldn't. Looks like it works fine in those but I'm aware sharp (and some other modules) due to a NPM bug. [https://github.com/npm/cli/issues/4828](https://github.com/npm/cli/issues/4828)

Removing package-lock.json should ideally fix the issue but I'll have to manually validate the fix. Can you please share your system details, specifically CPU type?

**Comment by danielholm** [comment]
I get the same error in docker:

```
Error: Could not load the "sharp" module using the linux-x64 runtime
astroluma          | Possible solutions:
astroluma          | - Ensure optional dependencies can be installed:
astroluma          |     npm install --include=optional sharp
astroluma          | - Ensure your package manager supports multi-platform installation:
astroluma          |     See https://sharp.pixelplumbing.com/install#cross-platform
astroluma          | - Add platform-specific dependencies:
astroluma          |     npm install --os=linux --cpu=x64 sharp
astroluma          | - Consult the installation documentation:
astroluma          |     See https://sharp.pixelplumbing.com/install
astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)
astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
astroluma          |     at Module.load (node:internal/modules/cjs/loader:1203:32)
astroluma          |     at Module._load (node:internal/modules/cjs/loader:1019:12)
astroluma          |     at Module.require (node:internal/modules/cjs/loader:1231:19)
astroluma          |     at require (node:internal/modules/helpers:177:18)
astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)
astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
astroluma          | 
astroluma          | Node.js v18.20.5
astroluma exited with code 1
```

**Comment by tiesoft** [comment]
> I get the same error in docker:
> 
> ```
> Error: Could not load the "sharp" module using the linux-x64 runtime
> astroluma          | Possible solutions:
> astroluma          | - Ensure optional dependencies can be installed:
> astroluma          |     npm install --include=optional sharp
> astroluma          | - Ensure your package manager supports multi-platform installation:
> astroluma          |     See https://sharp.pixelplumbing.com/install#cross-platform
> astroluma          | - Add platform-specific dependencies:
> astroluma          |     npm install --os=linux --cpu=x64 sharp
> astroluma          | - Consult the installation documentation:
> astroluma          |     See https://sharp.pixelplumbing.com/install
> astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)
> astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> astroluma          |     at Module.load (node:internal/modules/cjs/loader:1203:32)
> astroluma          |     at Module._load (node:internal/modules/cjs/loader:1019:12)
> astroluma          |     at Module.require (node:internal/modules/cjs/loader:1231:19)
> astroluma          |     at require (node:internal/modules/helpers:177:18)
> astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)
> astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> astroluma          | 
> astroluma          | Node.js v18.20.5
> astroluma exited with code 1
> ```

The same here in docker.

**Comment by Sanjeet990** [comment]
> > I get the same error in docker:
> > ```
> > Error: Could not load the "sharp" module using the linux-x64 runtime
> > astroluma          | Possible solutions:
> > astroluma          | - Ensure optional dependencies can be installed:
> > astroluma          |     npm install --include=optional sharp
> > astroluma          | - Ensure your package manager supports multi-platform installation:
> > astroluma          |     See https://sharp.pixelplumbing.com/install#cross-platform
> > astroluma          | - Add platform-specific dependencies:
> > astroluma          |     npm install --os=linux --cpu=x64 sharp
> > astroluma          | - Consult the installation documentation:
> > astroluma          |     See https://sharp.pixelplumbing.com/install
> > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)
> > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > astroluma          |     at Module.load (node:internal/modules/cjs/loader:1203:32)
> > astroluma          |     at Module._load (node:internal/modules/cjs/loader:1019:12)
> > astroluma          |     at Module.require (node:internal/modules/cjs/loader:1231:19)
> > astroluma          |     at require (node:internal/modules/helpers:177:18)
> > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)
> > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > astroluma          | 
> > astroluma          | Node.js v18.20.5
> > astroluma exited with code 1
> > ```
> 
> The same here in docker.

@tiesoft Which CPU and OS?

**Comment by tiesoft** [comment]
> > > I get the same error in docker:
> > > ```
> > > Error: Could not load the "sharp" module using the linux-x64 runtime
> > > astroluma          | Possible solutions:
> > > astroluma          | - Ensure optional dependencies can be installed:
> > > astroluma          |     npm install --include=optional sharp
> > > astroluma          | - Ensure your package manager supports multi-platform installation:
> > > astroluma          |     See https://sharp.pixelplumbing.com/install#cross-platform
> > > astroluma          | - Add platform-specific dependencies:
> > > astroluma          |     npm install --os=linux --cpu=x64 sharp
> > > astroluma          | - Consult the installation documentation:
> > > astroluma          |     See https://sharp.pixelplumbing.com/install
> > > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)
> > > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > > astroluma          |     at Module.load (node:internal/modules/cjs/loader:1203:32)
> > > astroluma          |     at Module._load (node:internal/modules/cjs/loader:1019:12)
> > > astroluma          |     at Module.require (node:internal/modules/cjs/loader:1231:19)
> > > astroluma          |     at require (node:internal/modules/helpers:177:18)
> > > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)
> > > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > > astroluma          | 
> > > astroluma          | Node.js v18.20.5
> > > astroluma exited with code 1
> > > ```
> > 
> > 
> > The same here in docker.
> 
> @tiesoft Which CPU and OS?

The host is an old Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz and i'm running Ubuntu24.04 on it. But it shouldn't matter in docker.
Docker version 27.3.1, build ce12230
Docker Compose version v2.29.7

**Comment by Sanjeet990** [comment]
> > > > I get the same error in docker:
> > > > ```
> > > > Error: Could not load the "sharp" module using the linux-x64 runtime
> > > > astroluma          | Possible solutions:
> > > > astroluma          | - Ensure optional dependencies can be installed:
> > > > astroluma          |     npm install --include=optional sharp
> > > > astroluma          | - Ensure your package manager supports multi-platform installation:
> > > > astroluma          |     See https://sharp.pixelplumbing.com/install#cross-platform
> > > > astroluma          | - Add platform-specific dependencies:
> > > > astroluma          |     npm install --os=linux --cpu=x64 sharp
> > > > astroluma          | - Consult the installation documentation:
> > > > astroluma          |     See https://sharp.pixelplumbing.com/install
> > > > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)
> > > > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > > > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > > > astroluma          |     at Module.load (node:internal/modules/cjs/loader:1203:32)
> > > > astroluma          |     at Module._load (node:internal/modules/cjs/loader:1019:12)
> > > > astroluma          |     at Module.require (node:internal/modules/cjs/loader:1231:19)
> > > > astroluma          |     at require (node:internal/modules/helpers:177:18)
> > > > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)
> > > > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > > > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > > > astroluma          | 
> > > > astroluma          | Node.js v18.20.5
> > > > astroluma exited with code 1
> > > > ```
> > > 
> > > 
> > > The same here in docker.
> > 
> > 
> > @tiesoft Which CPU and OS?
> 
> The host is an old Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz and i'm running Ubuntu24.04 on it. But it shouldn't matter in docker. Docker version 27.3.1, build ce12230 Docker Compose version v2.29.7

Awesome. Thank you for the response. Indeed that shouldn't matter.

Looks like I have a similar machine lying around in my lab and I can try to replicate it there. Will keep posted.

**Comment by tiesoft** [comment]
> > > > > I get the same error in docker:
> > > > > ```
> > > > > Error: Could not load the "sharp" module using the linux-x64 runtime
> > > > > astroluma          | Possible solutions:
> > > > > astroluma          | - Ensure optional dependencies can be installed:
> > > > > astroluma          |     npm install --include=optional sharp
> > > > > astroluma          | - Ensure your package manager supports multi-platform installation:
> > > > > astroluma          |     See https://sharp.pixelplumbing.com/install#cross-platform
> > > > > astroluma          | - Add platform-specific dependencies:
> > > > > astroluma          |     npm install --os=linux --cpu=x64 sharp
> > > > > astroluma          | - Consult the installation documentation:
> > > > > astroluma          |     See https://sharp.pixelplumbing.com/install
> > > > > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/sharp.js:113:9)
> > > > > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > > > > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > > > > astroluma          |     at Module.load (node:internal/modules/cjs/loader:1203:32)
> > > > > astroluma          |     at Module._load (node:internal/modules/cjs/loader:1019:12)
> > > > > astroluma          |     at Module.require (node:internal/modules/cjs/loader:1231:19)
> > > > > astroluma          |     at require (node:internal/modules/helpers:177:18)
> > > > > astroluma          |     at Object.<anonymous> (/app/server/node_modules/sharp/lib/constructor.js:10:1)
> > > > > astroluma          |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
> > > > > astroluma          |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> > > > > astroluma          | 
> > > > > astroluma          | Node.js v18.20.5
> > > > > astroluma exited with code 1
> > > > > ```
> > > > 
> > > > 
> > > > The same here in docker.
> > > 
> > > 
> > > @tiesoft Which CPU and OS?
> > 
> > 
> > The host is an old Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz and i'm running Ubuntu24.04 on it. But it shouldn't matter in docker. Docker version 27.3.1, build ce12230 Docker Compose version v2.29.7
> 
> Awesome. Thank you for the response. Indeed that shouldn't matter.
> 
> Looks like I have a similar machine lying around in my lab and I can try to replicate it there. Will keep posted.

Thank you @Sanjeet990 ! I'm really keen to try Astroluma.

**Comment by m10x** [comment]
https://github.com/Sanjeet990/Astroluma/pull/4/commits/8ee8456be1db80465a1937dc0257bd0bc3da42bb

This worked for me. First, `@rollup/rollup-linux-x64-gnu` was missing and then `sharp`

**Comment by tiesoft** [comment]
> [8ee8456](https://github.com/Sanjeet990/Astroluma/commit/8ee8456be1db80465a1937dc0257bd0bc3da42bb)
> 
> This worked for me. First, `@rollup/rollup-linux-x64-gnu` was missing and then `sharp`

I can confirm. I've rebuilt the image too. The solution of @m10x is working.

**Comment by danielholm** [comment]
And the new docker build is released when, you think? Or should I build it myself? Really looking forward to try this.
