### ISSUE TITLE
Cannot run on arm64

### ISSUE THREAD

**Issue by Niceygy** [Sanjeet990/Astroluma#5]
Hi! When running the docker compose example on arm64, it presents the following error
`exec /usr/local/bin/docker-entrypoint.sh: exec format error`

and then trying to build from source, npm install errors with this:

` Error: Cannot find module @rollup/rollup-linux-arm64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.`

Shout if I can provide any more detail! :D

**Comment by Sanjeet990** [comment]
Thank you for testing this out. ARM support is still untested.

For the later part, a new hotfix is merged in main that should fix the issue Cannot find module @rollup/rollup-linux-arm64-gnu

**Comment by janaxhell** [comment]
Exactly same here on Orange Pi 3 LTS:

`exec /usr/local/bin/docker-entrypoint.sh: exec format error`

and

`WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!   applies to all versions ≥5.0, any of 4.4 ≥4.4.19`

**Comment by SvenKribitz** [comment]
`exec /usr/local/bin/docker-entrypoint.sh: exec format error`
I get this error as well.
Running on a Raspberry Pi 5

**Comment by Sanjeet990** [comment]
The official docker hum image is compiled for multiple platforms including ARM. Since I don't have an ARM device and unfortunately I can not emulate it either, can you please test it?

https://getastroluma.com/docs/getting-started/installation#install-on-docker

**Comment by Sanjeet990** [comment]
Yeah. Have pushed newly compiled docker image for ARM platform.

**Comment by janaxhell** [comment]
Ok, what I see now is this error repeated over and over:

```
> astroluma@1.0.0 server
> cd server && npm run server
> astrolumaserver@1.0.0 server
> node server.js
node:events:495
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at Object.<anonymous> (/app/server/server.js:106:8)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
      
  port: 8000
}
Node.js v18.20.5
```

And same error as above for MongDB

```
WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
applies to all versions ≥5.0, any of 4.4 ≥4.4.19 
see https://jira.mongodb.org/browse/SERVER-71772
see https://jira.mongodb.org/browse/SERVER-55178
see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
```

**Comment by Sanjeet990** [comment]
Yeah. The PORTs are already in use. Please change them and try again. Should work

**Comment by Sanjeet990** [comment]
> Ok, what I see now is this error repeated over and over:
> 
> ```
> > astroluma@1.0.0 server
> > cd server && npm run server
> > astrolumaserver@1.0.0 server
> > node server.js
> node:events:495
>       throw er; // Unhandled 'error' event
>       ^
> Error: listen EADDRINUSE: address already in use :::8000
>     at Server.setupListenHandle [as _listen2] (node:net:1817:16)
>     at listenInCluster (node:net:1865:12)
>     at Server.listen (node:net:1953:7)
>     at Object.<anonymous> (/app/server/server.js:106:8)
>     at Module._compile (node:internal/modules/cjs/loader:1364:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
>     at Module.load (node:internal/modules/cjs/loader:1203:32)
>     at Module._load (node:internal/modules/cjs/loader:1019:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
>     at node:internal/main/run_main_module:28:49
> Emitted 'error' event on Server instance at:
>     at emitErrorNT (node:net:1844:8)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   code: 'EADDRINUSE',
>   errno: -98,
>   syscall: 'listen',
>   address: '::',
> �      
>   port: 8000
> }
> Node.js v18.20.5
> ```
> 
> And same error as above for MongDB
> 
> ```
> WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
> applies to all versions ≥5.0, any of 4.4 ≥4.4.19 
> see https://jira.mongodb.org/browse/SERVER-71772
> see https://jira.mongodb.org/browse/SERVER-55178
> see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
> see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
> ```
> 
> EDIT I have Portainer on port 8000, but I've mapped Astroluma to 8888, I don't know why it says 8000 is in use.

Because in environment you're having 800 and running in host mode:

 environment:
      PORT: 8000

**Comment by janaxhell** [comment]
Ok, I've removed port 8000 from Portainer (useless anyway) and now it works (yes!), but what are the credentials? I've tried admin/123456 and admin/admin, but they fail.

**Comment by Sanjeet990** [comment]
Because your MongoDb instance is not running. MongoDb needs ARMv8.2-A or higher.

Can you please try with 

 mongodb:
    image: mongo:4.0

**Comment by janaxhell** [comment]
Yes! With 4.0 I could login with admin/123456
Thanks, tomorrow I'll look into it and play with settings :)

**Comment by Sanjeet990** [comment]
> Yes! With 4.0 I could login with admin/123456 Thanks, tomorrow I'll look into it and play with settings :)

Awesome. Thank you.

**Comment by Sanjeet990** [comment]
ARM supported tested on 

- MAC Mini M1 by Sanjeet
- Google Cloud C4A Axion by Sanjeet
- OP of this this issue

And found working as expect with the latest tag of the docker image, hence closing.
