### ISSUE TITLE
Links open in new tab

### ISSUE THREAD

**Issue by dranoto** [Sanjeet990/Astroluma#55]
Can we have a setting to open the link in a new tab? It should probably be default behavior but I leave that to you.

**Comment by Sanjeet990** [comment]
Hi,

Open in New Tab is already a feature included in "Astroluma". The default behaviou is:

1. Link open in same Tab when the link tile is clicked.
2. Link open in new tab when opened by clicking the new tab icon.

![image](https://github.com/user-attachments/assets/ec2d4cb1-2971-45f4-9a82-4cec92b17b07)

"New Tab" icon is present on each link tile at the top right corner. Click on it to open the link in new tab.
