### ISSUE TITLE
MongoDB avx error and @rollup/rollup-linux-x64-musl not found

### ISSUE THREAD

**Issue by abd3-13** [Sanjeet990/Astroluma#6]
HI, interesting dashboard was trying to check it but encountered issues:

- when compiling while following [this](https://getastroluma.com/docs/getting-started/installation#install-on-virtual-machines) came to `Error: Cannot find module @rollup/rollup-linux-x64-musl` had to install it manually

- after a successful build when i run `server.js` : db not found, then pulled mongodb 6, run it but CPU avx error from the db container, so can't use it , is mongodb the only db supported or is there other plans?

**Comment by brkr1** [comment]
> * but CPU avx error

Use mongo 4.0

**Comment by Sanjeet990** [comment]
Using Mongo 4.0 by default now:

https://github.com/Sanjeet990/Astroluma/pull/14

Please test!

**Comment by abd3-13** [comment]
Works with Mongo 4,  is there any plans to support other DB?

**Comment by Sanjeet990** [comment]
Closing for now as worked for the OP.

As of now, not thinking for an alternative.
